name: ci-silverstripe-module
on:
  workflow_call:
    inputs:
      php-version:
        type: string
        required: false
        default: 7.4
      silverstripe-version:
        type: string
        required: false
        default: 4.9
      run-php-lint:
        type: boolean
        required: false
        default: false
      run-php-unit:
        type: boolean
        required: false
        default: true
      run-php-unit-coverage:
        type: boolean
        required: false
        default: false
      run-phpstan:
        type: boolean
        required: false
        default: false
      run-todo:
        type: boolean
        required: false
        default: false
      run-duplicate-code-check:
        type: boolean
        required: false
        default: false

      # SilverStripe requires an environment flag set in order to enable test only config, but unfortunately env vars
      # are not passed through when uses directive is used.  As such it will have to be passed in each time :(
      test-config-flag:
        type: string
        required: false
        default: THIS_IS_A_DUMMY_FLAG

jobs:
  ssmoduletests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      # Ensure all jobs run
      fail-fast: false

    steps:
      - name: Run Manticoresearch
        uses: gordonbanderson/manticoresearch-action

      - name: Alter env for test yml configuration in SS unit testing - optional
        run: |
          echo "${{ inputs.test-config-flag }}=1" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      # Not sure why this is required, but it fixes a missing cache dir issue
      - name: Ensure npm cache dir exists
        run: mkdir /home/runner/.npm

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install node packages
        run: npm install

      - name: Setup PHP ${{ inputs.php-version }} with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, zip

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install certain version of SilverStripe
        run: composer require --no-update silverstripe/recipe-cms:${{ inputs.silverstripe-version }}

      - name: Install dependencies
        # TODO Figure out why recipe removal and reinstall step has become necessary
        run: |
          composer install --prefer-dist --verbose --profile
          rm -rf vendor/silverstripe/recipe*
          composer install --prefer-dist --verbose --profile

      # This is configured to run against the service database
      - name: Set up .env file for database
        run: wget "https://raw.githubusercontent.com/silverstripe/github-actions-ci-cd/main/.github/things/.env"

      - name: Run Unit Tests
        if: ${{ inputs.run-php-unit }}
        run: |
          vendor/bin/phpunit tests

      - name: Lint Check
        if: ${{ inputs.run-php-lint }}
        run: vendor/bin/parallel-lint src/ tests/

      - name: PHP Unit Coverage
        if: ${{ inputs.run-php-unit-coverage }}
        run: |
          phpdbg -qrr vendor/bin/phpunit tests --coverage-clover=coverage.xml
          bash <(curl -s https://codecov.io/bash) -f coverage.xml

      - name: PHPStan
        if: ${{ inputs.run-phpstan }}
        run: |
          vendor/bin/phpstan analyse --level=8 -c tests/phpstan.neon src/

      - name: TODO
        if: ${{ inputs.run-todo }}
        run: |
          node_modules/leasot/bin/leasot -x tests --ignore **/*.neon

      - name: Duplication
        if: ${{ inputs.run-duplicade-code-check }}
        run: |
          node_modules/jscpd/bin/jscpd src
          node_modules/jscpd/bin/jscpd tests
