name: ci-silverstripe-module
on:
  workflow_call:
    inputs:
      php-version:
        type: string
        required: false
        default: 7.4
      run-phplinting:
        type: boolean
        required: false
        default: true
      run-phpunit:
        type: boolean
        required: false
        default: true


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      strategy:
        # Ensure all jobs run
        fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Not sure why this is required, but it fixes a missing cache dir issue
      - name: Ensure npm cache dir exists
        run: mkdir /home/runner/.npm

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install node packages
        run: npm install

      - name: Setup PHP ${{ inputs.php-version }} with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, zip

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # This is configured to run against the service database
      - name: Set up .env file for database
        run: wget "https://raw.githubusercontent.com/silverstripe/github-actions-ci-cd/main/.github/things/.env"

      - name: Run tests
        if: ${{ inputs.runphp-unit == true }}
        run: |
          export UNIT_TESTING_CONFIG_ENABLED=1
          vendor/bin/phpunit tests
