name: ci-silverstripe-module
on:
  workflow_call:
    inputs:
      run_phplinting:
        type: boolean
        required: false
        default: true
      run_phpunit:
        type: boolean
        required: false
        default: true


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
